App/app.py
# Importation de Flask et des Blueprints depuis les modules des routes
from flask import Flask
from routes.main_routes import main_bp

# Création d'une application Flask
app = Flask(__name__)

# Enregistrement le blueprint dans l'application Flask
app.register_blueprint(main_bp)

# Exécution de l'application si elle est directement exécutée
if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5000)

App/routes/main_routes.py
# Importation du Blueprint depuis Flask
from flask import Blueprint, render_template, request, redirect

# Création d'un objet Blueprint nommé 'main_bp' avec un préfixe d'URL '/'
main_bp = Blueprint('main', __name__, url_prefix='/')

# Définition d'une route pour l'URL '/' avec la méthode GET
@main_bp.route('/', methods=['GET'])
def index():
    return render_template('index.html')

# Définition d'une route pour l'URL '/submit' avec la méthode POST
@main_bp.route('/submit', methods=['POST'])
def submit():
    # Récupération des données du formulaire
    name = request.form['name']
    return f'Vous avez soumis le formulaire avec le nom: {name}'

App/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulaire</title>
</head>
<body>
  <h1>Page d'accueil</h1>
    <h2>Formulaire</h2>
    <form method="post" action="{{ url_for('main.submit') }}">
        <label for="name">Nom:</label><br>
        <input type="text" id="name" name="name"><br><br>
        <input type="submit" value="Soumettre">
    </form>
</body>
</html>